### ISSUE TITLE
'all planning applications' and 'last 12 months' look not identical but v similar feels something wrong

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-core#12]
@matkoniecz I just noticed that 'all planning applications' and 'last 12 months compared to since 2019  looks not exactly identical but too similar in the screenshot I took just now for the 'How to' manual. Could you check? feels something wrong as can't be this many in last 12 months compared with all since 2019
Images are here 
https://github.com/colouring-cities/manual/wiki/A1-How-to-use-the-Planning-Controls-section-&-Planning-Visualisation-Tool

**Comment by matkoniecz** [comment]
You are right! Thanks for this catch, that layer actually was broken (one of performance tests somehow ended in the actual code).

Thanks again for catching it!

**Comment by polly64** [comment]
@matkoniecz great!
