### ISSUE TITLE
COMMUNITIES SECTION- prevent likes for individual domestic buildings- only allow 'domestic typology' likes 

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-core#18]
@matkoniecz @fallipalaiologou @mdsimpson42 This is quite a priority  for planning/ user-well being as we hopefully will soon have a lot of local societies adding data 
@matkoniecz depending on how much time you have left this is something we need to look at though (to minimise time) only starred items .  Otherwise could you let @mdsimpson42 know, as one for us to prioritise this week

The Planning section is linked to the Community section where we are allowing people to 'like' buildings including homes. We need to block this and only allow them to like domestic _typologies_ not individual buildings. (They can still like like non-domestic individual buildings and typologies in the same way as now.)  This is because citizens have a different relationship with domestic buildings - emotional/personal attachment- than non-dom, and asking people to 'like' individual's homes will i realise cause problems in future as some homes will end up with far fewer likes than others. This doesn't matter for non-dom. We also need to change the 'Like ' key also to only visualise  liked _typologies._ so the key would read ' Like this type of building?'
I have starred items below which area priority

- [x] Add new sub cat question at start saying: 'Is the building a home/domestic building or a non-domestic building? *
@matkoniecz could you do this one so i can start classifying them ready to move domestic ones? 
- [x] Duplicate this question at the start of the the LAND USE section and link so they cross populate
- [x] Where user selects option for 'non-domestic' building keep options for subcats as existing *
- [x] Where user selects option for 'home/domestic building' do not allow 'like me' option only allow 'like this type of building' *
- [ ] Migrate all 'like' data to like typology'  for saftety and then work with PH to identify  non-dom buildings  which can be re-liked before too many more entries are added *
- [ ] Alter key to only include ' Like this type of building? *

**Comment by matkoniecz** [comment]
@polly64 

> Is the building a home/domestic building or a non-domestic building?

Is it really needed? Is it maybe duplicating landuse data already asking about use as dwellings?

**Comment by polly64** [comment]
@matkoniecz just let me know if this is too much within the time you have. 

**Remove yellow box saying new feature**

**Add blue box at the top of the page** saying _'Please add information on how well you think buildings work and how they are used, by clicking first on a building, then on the 'Edit' button, and then on the relevant box_ (Click boxes  again if you need to remove data you have added). 

**Then add the following questions**
**_'Is the building a home?'_** (with tick box next to it as we've done before)
**_'Or is it another type of building?'_** (with tick box)
_This isn't actually asked under Land Use but doesn't have to be duplicated as a more detailed classification system exists there  (we can later auto populate these boxes from land use as well) 

**Then put the map button in here**

**If the answer is 'a home'** then open up the following question:
**_'Do you think this type of building contributes to the city?'_** (omit the current 'no' option)
_If yes_ open up the following tick boxes- with an option to 'click all'
_'Because the external design contributes to the streetscape'
'Because the internal layout works well'
'Because the building can be easily adapted and reused'
'Because the building incorporates outside space'
'Because the construction method and materials are likely to be long-lasting'_

**If the answer is 'another type of building?'** then open up the following 2 questions:
**_'Do you like this building'_**
**_'Do you think this type of building contributes to the city?'_** (omit the current 'no' option)
_If yes_ open up the following tick boxes- with an option to 'click all'
_'Because the external design contributes to the streetscape'
'Because the internal layout works well'
'Because the building can be easily adapted and reused'
'Because the building incorporates outside space'
'Because the construction method and materials are likely to be long-lasting'_

**Change the key so that it visualises  only data relating to the 'Do you think this type of building contributes to the city?' question for both domestic and non-domestic buildings**

**Comment by matkoniecz** [comment]
I will look into it at Monday

**Comment by polly64** [comment]
many thanks

**Comment by matkoniecz** [comment]
@polly64 Would it be OK to hide (remove from view and visualization) things specific to home/non-home answer? Without deleting them?

This way someone flipping between home and non-home will not delete other data and this way it will be also a bit easier to implement.

This way data would be still visible in database downloads and object history.

**Comment by polly64** [comment]
@matkoniecz yes could do for the moment- my concern would be others could then visualise this in the longer term using open footprints. But ok for short term fix. Could you add at the same time on Phase 2 planning list so we don't forget?

**Comment by matkoniecz** [comment]
>  'Is the building a home?' (with tick box next to it as we've done before)

Note that it will not cover sheds/garages etc (not sure is "domestic" covering them)

I added also extra functionality to hide existing likes from map.

Before:

![screen](https://user-images.githubusercontent.com/899988/216275752-47e1ca98-aae5-4440-8c4e-f311e0d0eca5.png)

After (note how like visualisation is coming back after marking it as non-domestic):

![Peek 2023-02-02 09-53](https://user-images.githubusercontent.com/899988/216276900-10207399-815c-4105-a86f-e82c9541d867.gif)


Do you maybe want map visualisation which buildings are marked as homes or nonhomes and which are not?

@polly64 

> 'Is the building a home?' (with tick box next to it as we've done before)
> 'Or is it another type of building?' (with tick box)

Can it be like in gif above? (such split is annoying from a technical side)

**Comment by polly64** [comment]
@matkoniecz 
this looks great
yes like idea of if its's a home but to your point about sheds I think we would need to call it 'domestic buildings' not homes as this will cover everything in the garden other than private garages

not sure quite  understand your last point- main visualisation we need is for liked typologies. Domestic and non domestic building option for visualisation on key should really fall in Land Use section . I'm  in London today but can also have a meeting tomorrow if any help

**Comment by matkoniecz** [comment]
> not sure quite understand your last point- main visualisation we need is for liked typologies. Domestic and non domestic building option for visualisation on key should really fall in Land Use section .

I can add such visualisation (also in land use section), maybe temporarily, if that would be useful in filling this data. This part is relatively easy (would take about 20 minutes for yes/no visualisation of a single field) and may help to spot buildings with missing data.

**Comment by polly64** [comment]
@matkoniecz sounds great

**Comment by matkoniecz** [comment]
@polly64 

>  'Do you think this type of building contributes to the city?' (omit the current 'no' option)

is it supposed to replace "Do you think this type of building is generally worth keeping?" question?

**Comment by polly64** [comment]
@matkoniecz yes

**Comment by matkoniecz** [comment]
@polly64 And existing data should be kept, just name should be changed?

**Comment by polly64** [comment]
@matkoniecz yes

**Comment by matkoniecz** [comment]
@polly64 

>  Alter key to only include ' Like this type of building? *

What you mean by that? Not displaying like counts on the map for domestic buildings?

Not displaying like count at all?

I see later

> Change the key so that it visualises only data relating to the 'Do you think this type of building contributes to the city?' question for both domestic and non-domestic buildings

**Comment by polly64** [comment]
@matkoniecz never displaying 'like' counts for domestic buildings only typology 'like' counts

**Comment by matkoniecz** [comment]
Should we display like count for public buildings?

If we display typology like count for specific buildings on the map then it does not seem to be conceptually different.

**Comment by matkoniecz** [comment]
> with an option to 'click all'

I will move it to a separate issue as it is a bit trickier and already bunch of things is being changed.

**Comment by matkoniecz** [comment]
Changes deployed to https://cl-staging.uksouth.cloudapp.azure.com/edit/community/2481763

What is missing: 

should we display like counts for public buildings anywhere? Should we remove it from the map?

Not sure how well general public will distinguish liking type of building and specific building, especially if individual specific buildings will be painted based on rating of building type.

"with an option to 'click all'"

" Migrate all 'like' data to like typology' for saftety and then work with PH to identify non-dom buildings which can be re-liked before too many more entries are added *" - is it still needed with display blocked for buildings marked as domestic and ones with unknown state?

@polly64

**Comment by polly64** [comment]
@matkoniecz shall we have a quick chat tomorrow anytime between 9 am and 11 am?

**Comment by polly64** [comment]
@matkoniecz I agree the difference is slim maybe we can talk about this. I think we need to remove the thumbs up and word like from the key to help this. Just need to move to more anonymity. But I do think if you point to my house and say 'Do you like **this house**?' or if you say ' Do you like **this type of house?**' then I'd be less offended if they didn't colour my house and coloured the one next door

Btw where on staging need to just remove the 'is' in 'Do you think this type of building **is** contributes to the city?

**Comment by matkoniecz** [comment]
@polly64 That would work for me!

**Comment by polly64** [comment]
@matkoniecz let's go for 9am  tomorrow

**Comment by matkoniecz** [comment]
Work from home does not count as office and does not make building non-domestic.

**Comment by matkoniecz** [comment]
After all: we need domestic (yellow)/no-domestic (red)/mixed (orange)/not yet declared (no coloured) map.

And we need mixed domestic and domestic use  status.

**Comment by polly64** [comment]
@matkoniecz really getting there but think a few things need tweaking

- [x] 1. **Hide  the  domestic/non-domestic/mixed use option and put in Land Use**

- [x] 2. **Remove  non-domestic 'like' option and map but just hide**

- [x] 3. **Add 2 x big section headings that concertina as in Planning**
For section 1)
_How well do you think different types of building work?_
For section 2)
_Where are buildings used for community activities located?_

4. **Under the section headings add blue boxes with same font as planning , so we can explain what data are included** (remove other  existing blue boxes)
For section 1) 
- [x] '_Here we are collecting data on how well you think specific _types_ of building work (rather than individual buildings), to help ensure we save and reuse all useful buildings and to help improve urban design quality in future_.

For  section 2) 
- [x] '_Here we are collecting information on the location of buildings used for community activities so we can track loss of/additions to community space over time_'

5.  **Under the  blue boxes add the following questions**

For section 1) 

- [x] Add_Please tick if you like this _type_ of building and think it works well

(keep the following as now
- because the external design contributes to the streetscape
- because the internal design works well
- because the building is adaptable / can be reused to make the city more sustainable
- other)  

- [x] Change 'Do you think this building should be recorded as a local heritage asset?' to 'Do you think this building should be recorded as being of special local interest?'

For section 2) 
(Keep following questions as now
Are activities open to the community currently taking place in the building?
Has this ever been used for community activities in the past?
Has the building always been used for community activities?
Is the building in public/community ownership?)

- [ ] But replace dropdown for last question and use dropdown proposed for planning section instead, 

- [x] put question re link above the 'Click to see community use mapped' red button

**Comment by matkoniecz** [comment]
Hide complete like me for specific buildings, including map layer

**Comment by matkoniecz** [comment]
> Do you think this type of building is contributes to the city?

this should use standard yes button for community views

**Comment by polly64** [comment]
@matkoniecz @mdsimpson42 Mateusz these changes will all be on Colouing core repository from now on won't they?
Do you think we could release 'Community changes'  to Colouring London live site tomorrow?

**Comment by matkoniecz** [comment]
@polly64 I expect that I will complete it tomorrow, though not sure how much time will be from opening pull request and merging.
