### ISSUE TITLE
AGE & HISTORY

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-core#6]
T

**'Age and History'**  NEW main category: 
- [x] Edit main 'Age' category to read 'Age and History'
- [x] Add three subtitles 

- _'Building Age'_. (use same font size etc for all new subtitles)
- _'Lifespan and Site History'_
- _'Survival and Loss tracked using Historical Maps'_ 

- [x] Under _'Building Age'_ include all subcats from 'Age and add the following:
- [x] 'Cladding date' as a new subset under 'facade date' with verify button and separate source box
- [x] 'Date of significant extensions' with options for multiple dates with verify button and separate source box
- [x] 'Date of significant retrofits' with options for multiple dates with verify button and separate source box

- [x] Under _'Lifespan and site history'_ 'move all items in the Dynamics' category into this section
- [x] Under_'Survival and loss over 130 years'_ add the following
- A pink box (copy one in planning ) saying 'Click here for historical maps'-this to bring up historical map layer in same way as planning - could also chat to @matkoniecz about the way he did this- then select a 'current' building outlined in red and colour by ticking one of the following options
- The current footprint matches/almost exactly matches the historical map beneath, and/or is known to have been built before the map was made'
- The building core is the same as the historical map but has had multiple additions/changes
- The building no longer exists

**Comment by mdsimpson42** [comment]
Done on colouring-london, will copy to colouring-core later
