### ISSUE TITLE
RESILIENCE

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-core#8]

**Comment by polly64** [comment]
**'Resilience'**  NEW main category: 
Add the following all greyed out: 
- [x] 'Building age' link to existing subset under 'Age and History'
- [x] 'Typical typology lifespan'
- [x] 'Typology adaptability rating' 
- [x] 'Physical adaptability rating -within plot' 
- [x] 'Landuse adaptability rating'
- [x] 'Structural material lifespan rating'
- [x] 'Protection from demolition rating' 
- [x] 'Flood risk rating' 
- [x] 'Surface geology type' 
- [x] 'Average community value rating for typology'
- [x] 'Other rating'
- [x] 'Total resilience rating'

**Comment by matkoniecz** [comment]
is it already done? if not then it may be better to uncheck this tasks

**Comment by polly64** [comment]
@matkoniecz yes completed

**Comment by mdsimpson42** [comment]
Done on colouring-london, will copy to colouring-core later
