### ISSUE TITLE
Historical map and other layers - on and off activation

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-core#9]
Hi @mdsimpson42 thanks for activating historical map. Should the test for adding data you emailed about work on staging or live site? don't seem to be able to access it. Trying Euston now.

also -wanted to ask you and @matkoniecz what do do about Turing off these layers. At the moment you have to always manually turn off the layers. It's actually quite problematic  because once you've seen a layer you often want to click on another category and look at something different.  But if say you've turned the map on using the pink button (or in the dropdown) in Age and History and you nare ow  wanting to look at location data you have to remember to turn the historical map off or else where you land on location it will still be there. I wonder whether all layers for the moment should automatically turn off when you click outside the main category you are on (and then people can use the drop down to see layers unless pink buttons exist ? Is this easy to do?  Also is can you both suggest simpler ways to label them?

**Comment by mdsimpson42** [comment]
I was just thinking about this, in the context of adding the Key for the historical layers. Presumably, the key should change when the historical layer is activated and change back when its turned off. I'm not sure how easy this will be to do, but I'll look into it.

What about if you click on the "show historical maps" button on the layer options menu on the right? Should that be the same, or behave differently?

It should be possible to turn off the historical layer whenever the user switches categories, but I'll have to look into it.

**Comment by polly64** [comment]
@mdsimpson42 yes layer option should be linked to the pink button in the edit panel - 
Could we get this layer to work before 24th and add the  data option categories? 
Is it meant to load at present ? could be my computer

**Comment by mdsimpson42** [comment]
I have fixed the bug that meant the pink button only worked on certain buildings. It should be working now (or will be fixed in the next deployment). 

There is a separate issue for disabling the map when you change categories (https://github.com/colouring-cities/colouring-london/issues/1037) which I will look into later.
